// Random Message Sender
const lib = require('lib')({token: process.env.STDLIB_SECRET_TOKEN});


// To add more answers for your command, simply add them to this list!
let messagePrompts = [
  `❓ 1 kişiyi kurtarmak için on kişiyi öldürür müsün?`,
  `❓ Özgür irade diye bir şey var mı?`,
  `❓ Tanrı'nın var olduğunu nasıl anlarsınız? Yok mu?`,
  `❓ Hayatın anlamı nedir?`,
  `❓ Mutlak ahlak diye bir şey var mı?`,
  `❓ Doğa veya yetiştirme bir kişinin kişiliğini oluşturur mu?`,
  `❓ Özgürlük nedir? Gerçek özgürlük mümkün mü?`,
  `❓ Üzüntü olmadan mutluluğun ne olduğunu bilebilir miyiz?`,
  `❓ İyiyi kötülük olmadan anlayabilir miyiz?`,
  `❓ Gerçek nedir ve gerçekle aynı mıdır?`,
  `❓ Gerçek diye bir şey var mı, yoksa göreceli mi?`,
  `❓ Hiç üzülmemiş bir insan mutlu olabilir mi?`,
  `❓ Her şey nasıl ve ne zaman başladı?`,
  `❓ Neyin gerçek olup olmadığını nasıl anlarsınız?`,
  `❓ Yaşamın bir sebebi var mı ve nedir?`,
  `❓ Bir insana öldükten sonra ne olur?`,
  `❓ İnsanların bir ruhu var mı? Hayvanların bir ruhu var mı?`,
  `❓ Bir kişinin gözlemlediği, gerçekte olanı değiştirir mi?`,
  `❓ Gerçeği bilmek için kanıtımız olmalı mı?`,
  `❓ Neyin gerçek olduğunu nasıl anlarsın?`,
  `❓ Yerçekimi nedir ve nasıl çalışır??`,
  `❓ Bir insanın hayatı üzerinde ne kadar kontrolü vardır?`,
  `❓ Yalan söylemek her zaman yanlış mıdır? Ne zaman (eğer varsa) sorun olmaz?`,
  `❓ Kimse görmezse veya bilmiyorsa 'yanlış' bir şey yapmak doğru mudur?`,
  `❓ Kendi kaderinizi mi şekillendiriyorsunuz yoksa her şey kaderle mi oluyor?`,
  `❓ Sayılar gerçekten var mı yoksa insanın yarattığı bir şey mi?`,
  `❓ Tanrı 'iyi' ise, dünyada neden bu kadar çok kötülük var?`,
  `❓ Dünyanın ne zaman 'biteceğini' düşünüyorsunuz?`,
  `❓ İnsan bilinci ne zaman başlar?`,
  `❓ Düşünceler nelerdir ve nereden gelir?`,
  `❓ Ruh nedir? Yaşamdan önce var mı ve sonra mı devam ediyor?`,
  `❓ Paralel evrenler var mı?`,
  `❓ İnsanlara neden ölülere saygı duymaları söyleniyor?`,
  `❓ Hayatın amacı nedir?`,
  `❓ Herkesin hayatı eşit değerde mi?`,
  `❓ Din ve bilim uyumlu mu? Neden ya da neden olmasın?`,
  `❓ Hayatın en önemli amacı mutluluk mudur? Değilse nedir?`,
  `❓ Hangisi daha gerçek, akıl mı yoksa madde mi?`,
  `❓ Aşk nedir?`,
  `❓ İnsanlar paranın mutluluğu satın alamayacağını söylüyorlar, ama hiç parasız gerçekten mutlu olabilir misiniz?`,
  `❓ Dünyadaki tek bir şeyi değiştirebilseydin, bu ne olurdu?`,
  `❓ İyi bir arkadaşın özellikleri nelerdir?`,
  `❓ 'Çekim Yasası' var mı ve nedir?`,
  `❓ Gerçek aşk diye bir şey var mı?`,
  `❓ Sevgiye sahip olmak ve kaybetmek mi yoksa hiç sevmemek mi daha iyidir?`,
  `❓ Bilgisayarların dünyayı ele geçireceğini düşünüyor musunuz?`,
  `❓ Hangisi daha kolay - sevmek mi sevilmek mi?`,
  `❓ Biz buna 'aşık olma' diyoruz?`,
  `❓ Bir flört sitesinde bir koca arar mısın? Neden ya da neden olmasın?`,
  `❓ 'Vahşi' hayvanların evcil hayvan olarak tutulması gerektiğini düşünüyor musunuz? Ne zaman ve neden?`,
  `❓ İnsanların arkadaşa ihtiyacı var mı? Neden?`,
  `❓ Uyuşturucuyu yasaklıyorsak, neden zararlı gıda katkı maddeleri ve alkol olmasın?`,
  `❓ Eğer göremiyorsak elektronların ve kara deliklerin var olduğunu nasıl biliyoruz?`,
  `❓ Bir sır söylemekte hiç sakınca var mı?`,
  `❓ Sevdiğin birini kurtarmak için kanunları çiğner misin?`,
  `❓ En çok neden korkuyorsun?`,
  `❓ Piyangoyu kazanırsan işini bırakır mısın? Neden ya da neden olmasın?`,
  `❓ Çok az ödeme yapan sevdiğiniz bir işi mi yoksa çok para ödeyen nefret ettiğiniz bir işi mi tercih edersiniz?`,
  `❓ Zaman bir günden diğerine değişiyor mu ve bu yüzden bazı günler sonsuza kadar devam ediyor gibi görünüyor?`,
  `❓ Yarın öleceğini bilseydin, bugün ne yapardın?`,
  `❓ Yaşam evrenin başka bir yerinde mi var?`,
  `❓ Zihnimiz olasılıklı davranan parçacıklardan ve atomlardan oluşuyorsa, özgür iradeye sahip olduğumuzu nasıl düşünebiliriz?`,
  `❓ İyi ya da kötü hangi tarihsel figür sizce dünya üzerinde en büyük etkiye sahipti? Senin ülken?`,
  `❓ Şans diye bir şey var mı?`,
  `❓ Hangisi daha iyi bir evcil hayvan yapar - kedi mi yoksa köpek mi? Neden?`,
  `❓ Tüm alışverişlerin çevrimiçi yapılacağı bir zaman geleceğini düşünüyor musunuz?`,
  `❓ Hangi mevsim en iyisidir - yaz, kış, ilkbahar veya sonbahar? Neden?`,
  `❓ Palyaçolar komik mi yoksa korkutucu mu?`,
  `❓ Evlenmek için doğru yaş kaçtır?`,
  `❓ Lider mi yoksa takipçi mi daha önemli?`,
  `❓ Hayvanlar 'düşünebilir' ve / veya 'akıl yürütebilir' mi?`,
  `❓ Bir kişinin adı, kişiliği hakkında herhangi bir şey belirler mi?`,
  `❓ Neden evler odada kimse yokken sönen algılama ışıklarıyla donatılmıyor?`,
  `❓ Duygular mantıklı mı yoksa mantıksız mı?`,
  `❓ Evrensel insan hakları var mı? Onlar neler?`,
  `❓ Varsa hayvanların hakları nelerdir?`,
  `❓ Bilgisayarların yaratıcı olma yeteneği var mı?`,
  `❓ Savaşlar, ülkelerin ve hükümetlerin sorunlarını çözer mi?`,
  `❓ Her olayın bir nedeni var mı?`,
  `❓ İnsanlar gerçekten özgür iradeye sahip mi?`,
  `❓ Aşk cinsel arzudan farklı mıdır? Tutku? Nasıl?`,
  `❓ İnsanların ne kadar özgürlüğe sahip olmasına izin verilmeli?`,
  `❓ Sağlıksız yaşam tarzı yaşayanlar için hükümetlerin cezaları olmalı mı?`,
  `❓ Hükümet organ bağışını zorunlu hale getirmeli mi?`,
  `❓ İnsanların organlarını satmalarına izin verilmeli mi ve organ bağışçıları mali olarak tazmin edilmeli mi?`,
  `❓ Eyalet veya ülke sınırları olmaksızın insanların diledikleri her yerde yaşama ve seyahat etme hakları olmalı mı?`,
  `❓ Demokrasi her ülke için işe yarar mı?`,
  `❓ ABD'de doğum oranı düştüğü için, insanların en az bir çocuğu olması gerekir mi?`,
  `❓ Biri kendini öldürüyorsa ve siz sadece izliyor ve müdahale etmeyi reddediyorsanız, bu ölümden siz mi sorumlusunuz?`,
  `❓ Eşitsiz bir servet dağılımını önlemek için insanların kazanabilecekleri ve biriktirebilecekleri para miktarını sınırlamalı mıyız?`,
  `❓ Araba sürerken ve yolun kenarında bir ayakkabı gördüğünüzde, diğer ayakkabının başına ne geldiğini düşünüyorsunuz?`,
  `❓ İşkence haklı mı?`,
  `❓ Seçime sahip olmak her zaman iyi midir?`,
  `❓ Hangisi daha önemli, adalet mi merhamet mi?`,
  `❓ Bir ülkenin kültürünün korunması, göçü sınırlamak için iyi bir neden midir?`,
  `❓ Adil ticaret ile serbest ticaret arasında bir fark var mı? Nedir ve hangisi daha önemli?`,
  `❓ İnsanları ırka göre tanımlamak sosyal bir yapı mı yoksa biyolojik bir kategori mi?`,
  `❓ Zamanda yolculuk yapmak mümkün olacak mı? Eğer ki olursa bununla ilgili hayallerin?`,
  `❓ Ölümcül hastalığı olan kişilerin intihar etmesine izin verilmeli veya teşvik edilmeli mi?`,
  `❓ Yasayı çiğnemek hiç doğru mu? Neden ve ne zaman?`,
  `❓ Rüyalar nedir ve neden onlara sahibiz?`,
  `❓ Resmi bir eğitim olmadan bir kişi 'eğitilebilir' mi?`,
  `❓ Günümüz toplumunda şeref diye bir şey var mı? Onuru nasıl tanımlarsın?`,
  `❓ Günümüz dünyasında aile ne kadar alakalı?`,
  `❓ Hangisi daha önemli, saygı duyulacak veya beğenilecek?`,
  `❓ Hangisi daha iyi, iyi bir oyun oynayıp kaybetmek mi yoksa hile yapıp 'kötü' bir oyun oynamak ve kazanmak mı?`,
  `❓ İnsanlara işleri için ödeme yapma şeklimiz 'adil' mi yoksa insanlara uygun şekilde ödeme yapılmasını sağlamanın bir yolu olmalı mı? (yani futbolcular ve öğretmenler)`,
  `❓ Öz saygı tam olarak nedir ve nereden gelir?`,
  `❓ Sebzeler onları ısırdığınızda acı hissedebilir mi?`,
  `❓ Dibindeyken neden enginarın kalbi diyoruz?`,
  `❓ Bir sinemaya gittiğinizde koltuklarda kol dayama yeri varken hangisi sizin, hangisi komşularınız?`,
  `❓ Bir vejetaryen hayvan krakeri yemeli mi?`,
  `❓ Bir ineğin içinde süt neden bozulmaz, ama buzdolabının dışında bırakırsanız neden kötüleşir?`,
  `❓ Kel bir adamın ehliyetinde hangi saç rengi listelenir?`,
  `❓ Bir kişi tek kullanımlık bir tıraş bıçağı kaç kez kullanmalıdır?`,
  `❓ Arabalı banka makinelerinin sayı tuşlarında neden Braille alfabesi var?`,
  `❓ Dört kişiden beşinin kesirlerle sorun yaşadığı doğru mu?`,
  `❓ Kadınlar kendi yüz kıllarının çekici olmadığını düşündüğüne göre neden kaşlarını kazıtmıyorlar?`,
  `❓ Ters ananaslı kek, ananaslı ters kek olarak adlandırılmamalı mı?`,
  `❓ Gerçekten koyu kahverengi iken neden kremasız ve şekersiz kahveye “siyah” diyoruz?`,
  `❓ Hayatınıza bir saat eklemek için her gün egzersiz yapıyorsanız, egzersiz yapmak hayatınıza gerçekten saat eklememek için eklediğiniz fazladan saati kullanmıyor musunuz?`,
  `❓ Neden peynir ve öğle yemeği etlerini bir parça ekmekle aynı büyüklükte ve şekilde yapmıyorlar?`,
  `❓ Neden fare aromalı kedi maması alamıyorsun?`,
  `❓ Neden bir köpek suratına üflemekten nefret ediyor ama arabanın penceresinden kafasını dışarı çıkarmayı seviyor?`,
  `❓ Kadınlar maskara sürdüklerinde neden ağızlarını açarlar?`,
  `❓ Yün ıslandığında büzülürse, koyunlar yağmurda neden küçülmez?`,
  `❓ Neden bir tabutun kapağını çivilerler?`,
  `❓ Uçaklarda varken neden otobüslerde emniyet kemerleri yok?`,
  `❓ Neden koltuğunuzun altında bir uçakta paraşüt yerine bir yüzdürme cihazı var?`,
  `❓ Neden ayağımızın üstü ve elimizin arkası için bir adımız yok? Tabanın zıttı direk, avuç içinin zıttı salm olur mu?`,
  `❓ Yuvarlak pizzalar neden kare kutularda gelir?`,
  `❓ Kişi kaç yaşında 'yaşlı' olur?`,
  `❓ Evcil hayvanlarımızın bizim için isimleri var mı?`,
  `❓ İçinde kimse yokken aynalardan oluşan bir odanın neye benzediğini nasıl bilebilirsin?`,
  `❓ Perde ve örtü arasındaki fark nedir?`,
  `❓ Bıyık neden bir erkeğe çekici gelirken bir kadına çekici gelmez?`,
  `❓ Biri size verdiyse ama sizde olduğunu kimsenin bilmesine izin veremezseniz, bir fili nerede ve nasıl saklarsınız?`,
  `❓ Bebekler dolgunsa neden sağlıklı ama aynı vücut yapısına sahip kadınlar şişman kabul ediliyor?`,
  `❓ Enayi ile lolipop arasında bir fark var mı? Varsa nedir?`,
  `❓ Gerçek ve doğru arasındaki ilişki nedir?`,
  `❓ Varlık nedir? Varlığın nitelikleri nelerdir?`,
  `❓ Fiziksel varlıkla metafizik varlık arasındaki ilişki nedir?`,
  `❓ Değişim nedir?`,
  `❓ Değer nedir? Değeri belirleyen etmenler nelerdir?`,
  `❓ Güzelliğin ölçütleri nelerdir?`,
  `❓ Seni her zaman güldüren GIF veya video nedir?`,
  `❓ Buluşmak için en sevdiğin yer neresidir?`,
  `❓ En sık dinlediğin şarkı hangisidir?`,
  `❓ Bir filmde bahsedilen en sevdiğin alıntı nedir?`,
  `❓ Seni her zaman güldüren en iyi şaka hangisidir?`,
  `❓ Sence en iyi girişe sahip şarkı hangisidir?`,
  `❓ Otobüse binerken yanında taşıyabileceğin en korkutucu şey nedir?`,
  `❓ Bugüne kadar aldığın en komik veya en tuhaf mesaj neydi?`,
  `❓ Sadece resimlerle kaç soru cevaplayabilirsin?`,
  `❓ Şu an yanında yer alan en ilginç şey nedir?`,
  `❓ Telefonunda yer alan hangi uygulamayı kullanmamı önerirsin?`,
  `❓ Bugüne kadar çektiğin en iyi fotoğraf hangisidir?`,
  `❓ Yanlışlıkla gönderdiğin en kötü mesaj nedir?`,
  `❓ Şu anda satın almayı gerçekten çok istediğin şey nedir?`,
  `❓ Birinin internet üzerinden satın alabileceği en komik şey nedir?`,
  `❓ Telefonundaki en komik resim nedir?`,
  `❓ Seni tavlamak için kullanılan en aptalca sözcük hangisiydi?`,
  `❓ Senin için bazı yazılı olmayan kurallar nelerdir?`,
  `❓ Gerçek hayatta olan ama filmlerde pek yer bulmayan şeyler nelerdir?`,
  `❓ Gerçek olmayan ama umutsuzca olmasını istediğin şey nedir?`,
  `❓ Bugüne kadar bulduğun en iyi “gizli mücevher” nedir?`,
  `❓ Tutku duyduğun en saçma şey nedir?`,
  `❓ Telefonunla ilgili en çok neyden nefret ediyorsun?`,
  `❓ Son zamanlarda web ortamında gördüğün en saçma şey nedir?`,
  `❓ Her zaman hayalini kurduğun bir kariyer hedefine sahip misin?`,
  `❓ Bir iş kurmak zorunda olsaydın bu ne olurdu?`,
  `❓ Eğlenceli iş arkadaşlarına sahip misin?`,
  `❓ Yaşadığın konumla ilgili en çok neyi seviyorsun?`,
  `❓ Şehrin herhangi bir yerinde yaşasaydın nerede yaşardın?`,
  `❓ Odan neye benziyor?`,
  `❓ Yaşadığın yeri ev gibi hissettiren en önemli nesne nedir?`,
  `❓ Çocukluğundan beri sahip olduğun herhangi bir hobin var mı?`,
  `❓ Yaşamak için yapmak zorunda olsaydın hobinin tadını çıkarabilir miydin?`,
  `❓ Gevşemek için en sevdiğin yol nedir?`,
  `❓ Çocukken hangi oyunları oynardın?`,
  `❓ Herhangi bir sporcuyla görüşecek olsaydın bu kim olurdu?`,
  `❓ Hiç Tirübüne katıldın mı?`,
  `❓ Gardırobun tam olarak neye benziyor?`,
  `❓ Tarzını tarif edebilseydin bu ne olurdu?`,
  `❓ En çok hangi rengi giymeyi seversin?`,
  `❓ Seksi görünmek istiyorsan hangi kıyafeti giyersin?`,
  `❓ En sevdiğin müzik türü hangisidir?`,
  `❓ En son keşfettiğin müzik nedir?`,
  `❓ Tekrar tekrar dinlemeye doyduğun şarkı hangisidir?`,
  `❓ Şimdiye kadar en sevdiğin 3 şarkıyı sayar mısın?`,
  `❓ Üzerinde en büyük etkiyi hangi film yaptı?`,
  `❓ Film setleri gerçek olsaydı en çok hangi evreni ziyaret etmek isterdin?`,
  `❓ Kendini en çok hangi film karakteriyle özdeşleştiriyorsun?`,
  `❓ Senin favori yemeğin ne?`,
  `❓ Bir yemeği mükemmel bir şekilde yapacak olsan bu ne olurdu?`,
  `❓ En kötü restoran deneyimin nedir?`,
  `❓ Şimdiye kadar denediğin en tuhaf yiyecek nedir?`,
  `❓ Her hafta gitmen gereken bir restoran olsaydı nereyi tercih ederdin?`,
  `❓ Ne sıklıkla kitap okursun?`,
  `❓ Kurgusal kitaplar mı kurgusal olmayan kitaplar mı?`,
  `❓ Kağıt mı e-kitap mı?`,
  `❓ Bana bir kitap önersen bu ne olurdu?`,
  `❓ Hiç hayatını değiştiren bir kitap oldu mu?`,
  `❓ Ne tür bir kitap okumayı kesinlikle reddedersin?`,
  `❓ Herhangi bir yazarla tanışabilecek olsaydın kimi seçerdin?`,
  `❓ Hangi kitabın bir gün dizi veya film olmasını umut ediyorsun?`,
  `❓ Nefret ettiğin en popüler kitap nedir?`,
  `❓ Birlikte bir dizi izleyecek olsaydık hangisini seçerdin?`,
  `❓ Bir diziyi tamamen unutup yeniden izleyecek olsan tercihin ne olurdu?`,
  `❓ En çılgın tatil deneyimin hangisiydi?`,
  `❓ Asla yorulmadan tatil yapabilirim dediğin yer neresi?`,
  `❓ Seyahat etmek ufkunun genişlemesine yardımcı oldu mu?`,
  `❓ Hafta sonu birlikte seyahat edebilecek olsaydık neresini tercih ederdin?`,
  `❓ Yarın herhangi bir yerde uyanabilecek olsaydın bu neresi olurdu?`,
  `❓ Asla gitmek istemeyeceğin yer neresidir?`,
  `❓ Herhangi bir hayvan evcil hayvanın olacak olsaydı hangisini seçerdin?`,
  `❓ Büyürken hangi evcil hayvanlara sahiptin?`,
  `❓ Geçmişteki evcil hayvanlarına hangi isimleri verdin?`,
  `❓ Evcil hayvan sahibi olmanın en zor yanı nedir?`,
  `❓ Hangi konu hakkında çoğu insandan daha çok şey biliyorsun?`,
  `❓ Star Wars serisi mi Star Trek serisi mi?`,
  `❓ Elf ırkı mı Orc ırkı mı?`,
  `❓ Mario evreninden en sevdiğin karakter hangisi?`,
  `❓ DC evreni mi Marvel evreni mi?`,
  `❓ Zaman yolculuğu mümkün mü değil mi?`,
  `❓ Hogwarts’a gitseydin hangi gruba dahil olurdun?`,
  `❓ Manga okuyor musun veya anime izliyor musun?`,
  `❓ Doctor Who serisinde en sevdiğin doktor kim?`,
  `❓ Podcast dinlemeyi seviyor musun?`,
  `❓ Bir daha asla yaşamak istemeyeceğin bir anın var mı?`,
  `❓ Banka hesabında bir milyar dolar olsaydı o parayla ne yapardın?`,
  `❓ Sabah erkenden kalkmana yardımcı olan motivasyon nedir?`,
  `❓ Hayatımda olmazsa olmaz yapamam dediğin üç şey nedir?`,
  `❓ Son üç yılda ne kadar değiştin?`,
  `❓ Hiç korkun olmasaydı hayat nasıl olurdu?`,
  `❓ Kararlarını mantığa göre mi yoksa kalbine göre mi veriyorsun?`,
  `❓ Zor bir günün ardından gelen en iyi son nedir?`,
  `❓ Kendinle ilgili en çok neyi değiştirmek istersin?`,
  `❓ Dünyada bir şeyi değiştirebilecek olsaydın neyi değiştirirdin?`,
  `❓ Müzik dinlerken sözcükler mi yoksa melodi mi senin için daha önemlidir?`,
  `❓ Hayatta ki misyonun nedir?`,
  `❓ İnsanlar değişebilir mi?`,
  `❓ Bu aralar ne okuyorsun?`,
  `❓ Bugünün en iyi yanı neydi?`,
  `❓ Sana ilham veren şey ne?`,
  `❓ En çok hangi aksesuarını seviyorsun?`,
  `❓ Lider misin yoksa takipçi mi?`,
  `❓ Kin güder misin? `,
  `❓ Sabırsızlıkla beklediğin bir şey var mı?`,
  `❓ Neyin peşindesin? Macera mı yoksa güvenlik mi?`,
  `❓ Seni ‘sen’ yapan şey nedir?`,
  `❓ Bugün daha fazlasına ihtiyaç duyduğun şey nedir?`,
  `❓ Bugün hangi sanat akımı seni daha iyi anlatıyor?`,
  `❓ Neyi unutmak istersin?`,
  `❓ Kim olmak istiyorsun?`,
  `❓ Yarın ne yapmaya kararlısın?`,
  `❓ On üzerinden puan vererek cevapla: Ne kadar üzgünsün? Neden?`,
  `❓ Satın alman gereken üç şey nedir?`,
  `❓ Bugün bir hayvan olsaydı, hangi hayvan olurdu?`,
  `❓ Bu aralar önündeki en büyük engel nedir?`,
  `❓ İnsanlara en çok hangi soruyu sormayı seviyorsun? `,
  `❓ Bugüne dair bir şey değiştirebilecek olan neyi değiştirirdin?`,
  `❓ Son zamanlarda kredi kartı ekstrene düşen en utanç verici harcama hangisiydi?`,
  `❓ Aklında kalan en son rüya nasıldı?`,
  `❓ Atmayı aklından bile geçiremeyeceğin bir şey yaz.`,
  `❓ Neyi denemek pek iyi bir fikir sayılmaz?`,
  `❓ Bugün isteyip de elde edemediğin şey neydi?`,
  `❓ Güne bir saat daha ekleyebilseydin o saatte ne yapardın?`,
  `❓ Ne hakkında konuşmak istemezsin?`,
  `❓ Üç kelime ile inanç dünyanı anlat.`,
  `❓ İş ahlakından bahset.`,
  `❓ Bugün neyin hayalini kurdun?`,
  `❓ Kimin gibi olmayı isterdin?`,
  `❓ Kendini en son ne zaman bulutların üstünde hissettin? `,
  `❓ Hangi icatlar olmadan yaşayamazsın?`,
  `❓ Kendini en yakın hissettiğin kişi kim?`,
  `❓ Tek bir dilek hakkın olsa bugün neyin gerçekleşmesini isterdin? Sadece bir günlüğüne.`,
  `❓ Gizli tutkun nedir?`,
  `❓ Yeni öğrendiğin bir şeyi yaz.`,
  `❓ Hiç çaba göstermeden bir yetenek elde edilebilecek olsan bunun ne olmasını isterdin?`,
  `❓ En büyük eksikliğin nedir?`,
  `❓ ‘Ne iş yapıyorsun’ sorusuna nasıl cevap vermek isterdin?`,
  `❓ Tarihte hangi olayın gerçekleşmesini engellemek isterdin?`,
  `❓ Hayat adil mi? Evet? Hayır? Bazen? Bugün değil?`,
  `❓ Ne ‘tür’ bir insansın?`,
  `❓ Kiminle bir günlüğüne yer değiştirmek istersin?`,
  `❓ Sosyal hayatını üç kelime ile nasıl özetlersin? `,
  `❓ Bu günlük bir süper güce sahip olabilsen bu ne olurdu?`,
  `❓ Hayatını filme çekseler seni kim oynar? İyi bir film olur mu?`,
  `❓ Nasıl hatırlanmak istersin?`,
  `❓ Birini iyi bir düşman yapan özellikler nelerdir?`,
  `❓ En büyük başarın olarak gördüğün şey nedir?`,
  `❓ Bu hafta en çok hangi günü sevdin? Ne oldu?`,
  `❓ Zamanda geriye gidip bir şeyleri değiştirebilecek olsan bu ne olurdu?`,
  `❓ Son zamanlarda yaptığın en yaratıcı şey neydi?`,
  `❓ Aşk uğruna yaptığın en çılgınca şey neydi?`,
  `❓ Bugün sorumlulukların olmasa ne yapardın?`,
  `❓ On üzerinden puan vererek cevapla: Ne kadar sağlıklısın?`,
  `❓ İç güdülerine güvenmeli misin? Güvenir misin?`,
  `❓ Şu an en çok kimi özlüyorsun? `,
  `❓ İyi bir arkadaş hangi özellikleri taşır?`,
  `❓ Önünde bir engel var mı? Kaldırabilecek misin?`,
  `❓ Otobiyografinin ilk cümlesini yaz.`,
  `❓ Kimi daha iyi tanımak isterdin?`,
  `❓ En son ne zaman ağladın?`,
  `❓ En yakın yoldaşın kim?`,
  `❓ Ruh halin hava durumu olsaydı nasıl olurdu?`,
  `❓ Şu an, olmadan da yaşayabileceğin şey nedir?`,
  `❓ Okuma listenin ilk sırasında hangi kitap var?`,
  `❓ Kaybedecek neyin var?`,
  `❓ Bir roman kahramanı olsan hangisi olurdun?`,
  `❓ Mükemmel günü tarif et.`,
  `❓ İyi fikirler için nereye gidersin? `,
  `❓ Portreni çizdirecek olsan çizdirecek olsan gelmiş geçmiş tüm ressamlar arasından kimi seçerdin?`,
  `❓ Çalışıyor musun çalışıyor gibi mi yapıyorsun?`,
  `❓ Şu ana kadar yılın nasıl geçtiğini özetleyen bir şey yaz.`,
  `❓ Bugün sıradışıydı çünkü:`,
  `❓ Ne hakkında yalan söylersin?`,
  `❓ En son attığın telefon mesajını yaz.`,
  `❓ Bugün vücudunun en çok hangi yanından hoşnutsun?`,
  `❓ Hangi soru (ya da soruları) cevaplamaya bayılırsın?`,
  `❓ Kimin tarafındasın?`,
  `❓ Neyi unutamıyorsun?`,
  `❓ Evet ya da hayır: Herkesin bir yedek planı olmalı.`,
  `❓ Yaratıcılık tarifin nedir?`,
  `❓ Hayatının şu anki en iyi yanı nedir?`,
  `❓ Zafer dansını nasıl tanımlarsın?`,
  `❓ Zevk aldığın en basit şey nedir?`,
  `❓ İnternette en son hangi videoyu seyrettin?`,
  `❓ Kimi kıskanıyorsun? `,
  `❓ İkinci sınıfa giden bir çocuğa neler tavsiye ederdin?`,
  `❓ Ufak ama kronik bir sorununu yaz.`,
  `❓ Sana kim yardım edebilirdi?`,
  `❓ Hayatındaki en önemli insanlar kim?`,
  `❓ Hangi bölümde okumak isterdin?`,
  `❓ En sevdiğin abur cubur nedir?`,
  `❓ Bugün aldığın bir kararı yaz.`,
  `❓ Yakın zamanda hangi yeni mekana gittin?`,
  `❓ Reddedilmeyi kaldırabiliyor musun?`,
  `❓ Kötü haberleri doğrudan duymayı mı yoksa yumuşatılmalarını mı tercih edersin?`,
  `❓ Sana ne kendini harika hissettirir?`,
  `❓ Anlayış gösteremeyeceğin şey nedir?`,
  `❓ Vücudun hakkında ne düşünüyorsun?`,
  `❓ Kamp mı otel mi?`,
  `❓ Nerede duracağını kestirebilenlerden misin?`,
  `❓ İsteyip de yapamadığın bir şey oldu mu?`,
  `❓ Bu aralar en büyük masrafın nedir? `,
  `❓ Ne hiç değişmemeli?`,
  `❓ Hangi konuda konuşmak seni sıkıyor?`,
  `❓ Hangi konuda içini dökmen gerekiyor?`,
  `❓ Mezar taşında ne yazsın istersin?`,
  `❓ Sonun nasıl geleceğini bilmek ister miydin?`,
  `❓ Seni etkileyici kılan nedir?`,
  `❓ Yeni bir şehre taşınmak zorunda olsan bu hangisi olurdu?`,
  `❓ Hayallerinde ki tatili anlat.`,
  `❓ En son ne zaman huzurlu hissettin?`,
  `❓ Bu senenin en güzel anısı neydi?`,
];

{
  let messageChoice = Math.floor(Math.random() * messagePrompts.length);
  let message = messagePrompts[messageChoice];
   
  await lib.discord.channels['@0.0.6'].messages.create({
    channel_id: `${context.params.event.channel_id}`,
    content: `${message}`
  }); 
}